### PR TITLE
Spit out error when  unable to retrieve version from SolidServer

### PR DESCRIPTION
**Pull request by jarmbruster74**

### CODE REVIEW

**Review by wylie-ucb — DISMISSED** [review]
I disconnected from our VPN, and got this as a result :)

Error: SOLIDServer - Error retrieving SOLIDserver Version (No Answer): [Get "https://ddi.int.colorado.edu/rest/member_list?WHERE=member_is_me%3D%271%27": dial tcp: lookup ddi.int.colorado.edu: no such host]

**Comment by wylie-ucb** [comment]
NOTE:  I munged the password, and got the same output :/  Maybe there isn't any more detail that can be captured from the DDI response??
Error: SOLIDServer - Error retrieving SOLIDserver Version (No Answer): [Get "https://ddi.int.colorado.edu/rest/member_list?WHERE=member_is_me%3D%271%27": dial tcp: lookup ddi.int.colorado.edu: no such host]

**Comment by wylie-ucb** [comment]
I wasn't connected to the VPN for the bad password test.  I get this re-running the test (no additional outut):

Error: SOLIDServer - Error retrieving SOLIDserver Version (No Answer): []

**Comment by hexmoose** [comment]
We have switched back to the upstream fork. Archiving this repo.

**Pull request closed without merging**
